# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "Z:\\home\\benni\\psu\\metode\\udviklingsmetode\\api"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "Z:\\home\\benni\\psu\\metode\\udviklingsmetode\\api:/app:rw"
    - "Z:\\home\\benni\\psu\\metode\\udviklingsmetode\\api:/src:rw"
    - "C:\\Users\\benni\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
