services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    mem_limit: 2g
    cpus: "2.0"

volumes:
  rabbitmq_data:
